# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/plane/Documents/ETSIT/DSED/PROYECTO/dsed_audio/dsed_audio.cache/wt [current_project]
set_property parent.project_path C:/Users/plane/Documents/ETSIT/DSED/PROYECTO/dsed_audio/dsed_audio.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/plane/Documents/ETSIT/DSED/PROYECTO/dsed_audio/dsed_audio.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/plane/Documents/ETSIT/DSED/PROYECTO/dsed_audio/dsed_audio.srcs/sources_1/imports/BLOQUE1/interfaz_microfono/interfaz_microfono.srcs/sources_1/new/package_dsed.vhd
  C:/Users/plane/Documents/ETSIT/DSED/PROYECTO/dsed_audio/dsed_audio.srcs/sources_1/imports/BLOQUE1/generador_en_salida_clk_micro/generador_en_salida_clk_micro.srcs/sources_1/new/en_4_cycles.vhd
  C:/Users/plane/Documents/ETSIT/DSED/PROYECTO/dsed_audio/dsed_audio.srcs/sources_1/imports/BLOQUE1/interfaz_microfono/interfaz_microfono.srcs/sources_1/new/FSMD_microphone.vhd
  C:/Users/plane/Documents/ETSIT/DSED/PROYECTO/dsed_audio/dsed_audio.srcs/sources_1/imports/new/pwm.vhd
  C:/Users/plane/Documents/ETSIT/DSED/PROYECTO/dsed_audio/dsed_audio.srcs/sources_1/new/audio_interface.vhd
  C:/Users/plane/Documents/ETSIT/DSED/PROYECTO/dsed_audio/dsed_audio.srcs/sources_1/imports/new/controlador.vhd
  C:/Users/plane/Documents/ETSIT/DSED/PROYECTO/dsed_audio/dsed_audio.srcs/sources_1/new/data_path.vhd
  C:/Users/plane/Documents/ETSIT/DSED/PROYECTO/dsed_audio/dsed_audio.srcs/sources_1/new/control_filter.vhd
  C:/Users/plane/Documents/ETSIT/DSED/PROYECTO/dsed_audio/dsed_audio.srcs/sources_1/imports/PROYECTO/fir_filter.vhd
  C:/Users/plane/Documents/ETSIT/DSED/PROYECTO/dsed_audio/dsed_audio.srcs/sources_1/new/dsed_audio.vhd
  C:/Users/plane/Documents/ETSIT/DSED/PROYECTO/dsed_audio/dsed_audio.srcs/sources_1/new/bit_converter.vhd
  C:/Users/plane/Documents/ETSIT/DSED/PROYECTO/dsed_audio/dsed_audio.srcs/sources_1/new/controller_system.vhd
}
read_ip -quiet C:/Users/plane/Documents/ETSIT/DSED/PROYECTO/dsed_audio/dsed_audio.srcs/sources_1/ip/clk_12Mhz/clk_12Mhz.xci
set_property used_in_implementation false [get_files -all c:/Users/plane/Documents/ETSIT/DSED/PROYECTO/dsed_audio/dsed_audio.srcs/sources_1/ip/clk_12Mhz/clk_12Mhz_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/plane/Documents/ETSIT/DSED/PROYECTO/dsed_audio/dsed_audio.srcs/sources_1/ip/clk_12Mhz/clk_12Mhz.xdc]
set_property used_in_implementation false [get_files -all c:/Users/plane/Documents/ETSIT/DSED/PROYECTO/dsed_audio/dsed_audio.srcs/sources_1/ip/clk_12Mhz/clk_12Mhz_ooc.xdc]

read_ip -quiet C:/Users/plane/Documents/ETSIT/DSED/PROYECTO/dsed_audio/dsed_audio.srcs/sources_1/ip/RAM/RAM.xci
set_property used_in_implementation false [get_files -all c:/Users/plane/Documents/ETSIT/DSED/PROYECTO/dsed_audio/dsed_audio.srcs/sources_1/ip/RAM/RAM_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/plane/Documents/ETSIT/DSED/PROYECTO/dsed_audio/dsed_audio.srcs/constrs_1/imports/LABORATORIO/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files C:/Users/plane/Documents/ETSIT/DSED/PROYECTO/dsed_audio/dsed_audio.srcs/constrs_1/imports/LABORATORIO/Nexys4DDR_Master.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top dsed_audio -part xc7a100tcsg324-1 -retiming


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef dsed_audio.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file dsed_audio_utilization_synth.rpt -pb dsed_audio_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
