# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/plane/Documents/ETSIT/DSED/PROYECTO/dsed_audio/dsed_audio.srcs/sources_1/ip/clk_12Mhz/clk_12Mhz.xci
# IP: The module: 'clk_12Mhz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/plane/Documents/ETSIT/DSED/PROYECTO/dsed_audio/dsed_audio.srcs/sources_1/ip/clk_12Mhz/clk_12Mhz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_12Mhz'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/plane/Documents/ETSIT/DSED/PROYECTO/dsed_audio/dsed_audio.srcs/sources_1/ip/clk_12Mhz/clk_12Mhz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_12Mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/plane/Documents/ETSIT/DSED/PROYECTO/dsed_audio/dsed_audio.srcs/sources_1/ip/clk_12Mhz/clk_12Mhz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_12Mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/plane/Documents/ETSIT/DSED/PROYECTO/dsed_audio/dsed_audio.srcs/sources_1/ip/clk_12Mhz/clk_12Mhz.xci
# IP: The module: 'clk_12Mhz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/plane/Documents/ETSIT/DSED/PROYECTO/dsed_audio/dsed_audio.srcs/sources_1/ip/clk_12Mhz/clk_12Mhz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_12Mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/plane/Documents/ETSIT/DSED/PROYECTO/dsed_audio/dsed_audio.srcs/sources_1/ip/clk_12Mhz/clk_12Mhz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_12Mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/plane/Documents/ETSIT/DSED/PROYECTO/dsed_audio/dsed_audio.srcs/sources_1/ip/clk_12Mhz/clk_12Mhz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_12Mhz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
